### ISSUE TITLE
Zebranie informacji na temat możliwych technologii

### ISSUE THREAD

**Issue by qaziok** [Buzeqq/TERMINAL#1]

**Comment by Buzeqq** [comment]
# Aplikacja kliencka

## Możliwe podejścia
- **Aplikacja natywna**, czyli aplikacja stworzona dla konkretnego systemu (na spotkaniu odrzuciliśmy takie technologie jak: React Native i Flutter), działająca bezpośrednio na urządzeniu.
- **Progresive Web App** (PWA), czyli aplikacja wieloplatformowa, wymagana jest tylko możliwość uruchomienia przeglądarki.

## Porównanie

Największą zaletą **PWA** jest to, że jest niezależna od systemu urządzenia, które chce z niej skorzystać. W naszym przypadku oznacza to, że użytkownicy nie będą ograniczani tylko do urządzeń mobilnych z systemem Android. Wadą natomiast jest to, że **PWA** nie ma dostępu do wszystkich funkcjonalności urządzenia mobilnego, przez to, że działa w przeglądarce zużywa więcej baterii oraz nie jest tak szybka jak aplikacja natywna. D

## Technologie PWA
### Angular
Angular to popularny, rozbudowany i zaawansowany framework front-endowy opracowany przez Google. Jest oparty na języku TypeScript i pozwala na tworzenie dynamicznych aplikacji internetowych oraz PWA. Angular oferuje pełny zestaw narzędzi i funkcji, takich jak dwukierunkowe wiązanie danych, obsługa zdarzeń, zarządzanie stanem, obsługa routingu, testowanie jednostkowe i wiele innych. Angular używa architektury komponentów, co pozwala na tworzenie modułów reużywalnych i skalowalnych. Ponadto Angular oferuje także zaawansowane mechanizmy optymalizacji i wydajności, takie jak lazy loading, dzięki czemu aplikacje stworzone z użyciem Angulara mogą być szybkie i efektywne.

### Vue.js
Vue.js to progresywny framework JavaScript, który jest elastyczny, łatwy do nauki i zintegrowany z innymi bibliotekami lub istniejącymi projektami. Vue.js opiera się na konceptach komponentów i oferuje prostą składnię, dzięki czemu jest przyjazny dla początkujących oraz doświadczonych programistów. Może być używany zarówno jako biblioteka do rozbudowy istniejących stron internetowych, jak i jako pełnoprawny framework do tworzenia zaawansowanych aplikacji. Vue.js posiada wiele przydatnych funkcji, takich jak dwukierunkowe wiązanie danych, system reaktywności, obsługa komponentów, zarządzanie stanem, routowanie, animacje i wiele innych. Vue.js oferuje również oficjalne narzędzia i biblioteki do tworzenia PWA, takie jak Vue Router i VueX.

### PWA Builder
PWA Builder to narzędzie online, które pozwala na automatyzację procesu tworzenia PWA na podstawie istniejącej strony internetowej. Narzędzie to oferuje wiele gotowych szablonów i konfiguracji, które pozwalają na tworzenie PWA zgodnych z najnowszymi standardami. PWA Builder generuje pliki manifestu oraz serwisowego pracownika (service worker), które są niezbędne do funkcjonowania PWA, takich jak instalacja na ekranie głównym, obsługa offline, push notyfikacje i inne funkcje. Narzędzie to oferuje także testowanie i weryfikację PWA na różnych platformach, takich jak Android i iOS, co pozwala na upewnienie się, że aplikacja działa poprawnie na różnych urządzeniach i przeglądarkach.


## IndexedDB
IndexedDB to technologia bazodanowa w przeglądarkach internetowych, która pozwala na przechowywanie dużej ilości danych wewnątrz samej przeglądarki. Jest to rozszerzenie standardu JavaScript, które umożliwia zapisywanie danych w sposób asynchroniczny, co pozwala na efektywne zarządzanie danymi w trybie offline.

Wykorzystanie IndexedDB w PWA pozwala na przechowywanie danych na urządzeniu użytkownika, co umożliwia korzystanie z aplikacji bez połączenia internetowego. Można w ten sposób przechowywać dane takie jak obrazy, pliki dźwiękowe, dokumenty, a nawet całe struktury danych w formie obiektów JavaScript. IndexedDB działa asynchronicznie, co pozwala na efektywne zarządzanie dużymi ilościami danych, bez blokowania interfejsu użytkownika aplikacji.

Jako, że technologia IndexedDB nie jest najnowsza to jej api jest nieco przestarzałe, więc warto wykorzystać bibliotekę wrapper: [Dexie](https://dexie.org/)
