### ISSUE TITLE
Sortowanie danych pomiarowych

### ISSUE THREAD

**Issue by Buzeqq** [Buzeqq/TERMINAL#10]
Kryteria akceptacji:
- podczas przeglądania danych pomiarowych, możliwe jest sortowanie ich według podanego kryterium.
- użytkownik nie może wybrać kryterium, na którego podstawie nie da się posortować wyników.
- na interfejsie powinno być jasno i wyraźnie zaznaczone, że aktualny widok danych pomiarowych jest posortowany

**Comment by qaziok** [comment]
Duplicates #8
