### ISSUE TITLE
Zapoznanie się z biblioteką dexie.js

### ISSUE THREAD

**Issue by qaziok** [Buzeqq/TERMINAL#19]

**Comment by anton-0** [comment]
# Biblioteka dexie.js

## Ogólny opis

Biblioteka Dexie.js jest biblioteką JavaScript, która zapewnia interfejs do obsługi bazy danych IndexedDB w przeglądarkach internetowych. IndexedDB to wbudowana baza danych, która może być używana w aplikacjach internetowych, w tym w PWA (Progressive Web App). Dexie.js dostarcza prosty i wygodny sposób manipulacji danymi w IndexedDB, co czyni ją przydatną tworzeniu aplikacji PWA.

## Możliwości i cechy:

### 1. Zarządzanie bazą danych
Dexie.js umożliwia łatwe zarządzanie bazą danych IndexedDB w aplikacji PWA. Zapewnia prosty interfejs do wykonywania operacji CRUD (Create, Read, Update, Delete) na danych.

### 2. Asynchroniczność
Dexie.js obsługuje asynchroniczne operacje, co jest niezbędne w środowisku przeglądarki internetowej. Umożliwia to płynne działanie aplikacji PWA i uniknięcie blokowania interfejsu użytkownika

## Przykłady użycia
1. sticky note app - https://dev.to/andyhaskell/using-dexie-js-to-write-slick-indexeddb-code-304o

**Comment by qaziok** [comment]
Prototype in TerminalWeb folder
