### ISSUE TITLE
Research technologii Spring Boot

### ISSUE THREAD

**Issue by Buzeqq** [Buzeqq/TERMINAL#23]

**Comment by anton-0** [comment]
# Reasearch technologii Spring Boot 

## Główne zastosowania
Spring Boot jest frameworkiem dla języka Java, który pozwala na szybkie i łatwe tworzenie aplikacji webowych. Jest przeznaczony głównie do zarządzania relacyjnymi bazami danych, takimi jak MySQL, PostgreSQL, Oracle itp., za pomocą technologii Hibernate lub też Spring Data JPA.

## Możliwości
### 1. Dostarczenie API
Spring Boot może służyć jako backend, dostarczający API dla aplikacji PWA. Można zaimplementować RESTful API, które umożliwi komunikację między przeglądarką a serwerem.

### 2. Integracja z bibliotekami front-endowymi
Spring Boot pozwala na łatwe połączenie aplikacji back-endowej z bibliotekami front-endowymi, takimi jak Angular, React czy Vue.js.

### 3. Zarządzanie sesjami i uwierzytelnianiem
Spring Boot zapewnia mechanizmy do zarządzania sesjami użytkowników i uwierzytelniania. Można skonfigurować mechanizm uwierzytelniania, na przykład używając protokołu OAuth 2.0 lub JWT (JSON Web Token), aby umożliwić użytkownikom logowanie się do aplikacji PWA.

### 4. Obsługa bazy danych
Spring Boot oferuje bogaty zestaw narzędzi do obsługi różnych baz danych. Można użyć Spring Data JPA, aby łatwo mapować obiekty Java na rekordy w bazie danych i wykonywać operacje CRUD. To umożliwia przechowywanie i pobieranie danych związanych z aplikacją PWA.

### 5. Obsługa cachowania i trybu offline
Spring Boot pozwala na łatwe zarządzanie pamięcią podręczną aplikacji i jej zasobami, co umożliwia szybsze ładowanie i obsługę trybu offline.

## Zgranie z dexie.js i IndexedDB
Gdyby stworzyć aplikację która wykorzystuje zarówno Spring Boot jako backend, jak i IndexedDB jako bazę danych po stronie przeglądarki, to Spring Boot może dostarczać RESTful API do komunikacji z frontendem i zarządzania danymi w relacyjnej bazie danych po stronie serwera. Aplikacja frontendowa w przeglądarce może używać Dexie.js lub innego narzędzia do manipulacji danymi w samym środowisku przeglądarki i zarządzania bazą IndexedDB.

## Przykłady użycia
1. This is an example of a Progressive Web Application(PWA) with an Angular frontend and a Spring Boot backend with MongoDb. - https://github.com/Angular2Guy/AngularPwaMessenger
