### ISSUE TITLE
Wybór technologii frontendowej

### ISSUE THREAD

**Issue by Buzeqq** [Buzeqq/TERMINAL#5]
Element backlogu sprintu uznajemy za gotowy, gdy:
- Przeprowadzono odpowiedni research technologii,
- Sporządzono, krótkie sprawozdanie, które zawiera takie elementy jak np. wady i zalety,
- Sporządzono ostateczne porównanie technologii z tej samej kategorii,
- Technologia zaakceptowana przez każdego członka zespołu,
- Skonsultowano wybór z konsultantem i promotorem.

**Comment by qaziok** [comment]
For now Angular
